### ISSUE TITLE
Cannot assign to this block error

### ISSUE THREAD

**Issue by bhelx** [extism/js-sdk#70]
Getting this error after calling a plugin that's been alive for a long time. It's also manipulating variables a lot. Suspect it's a memory issue but wanted to see in what situations could this happen:

Tracked the error message to here: https://github.com/extism/js-sdk/blob/7f3c9a2ca113aff49d2fe8288e12a53bc8467601/src/call-context.ts#L224

```
Error: cannot assign to this block\n    at error_set (/Users/ben/
dylibso/xtprps/dist/index.js:67026:17)\n    at wasm://wasm/0074ea26:wasm-function[1355]:0xd362d\n   
 at wasm://wasm/0074ea26:wasm-function[1374]:0xd4f05\n    at ForegroundPlugin.callBlock (/Users/ben/
dylibso/xtprps/dist/index.js:67419:7)\n    at ForegroundPlugin.call (/Users/ben/dylibso/xtprps/dist/
index.js:67430:46)\n    at extensionPoints.<computed>.<computed> [as record] (/Users/ben/dylibso/xtp
rps/dist/index.js:69368:45)\n    at async record (/Users/ben/dylibso/xtprps/dist/index.js:69560:5)\n
    at async playGame (/Users/ben/dylibso/xtprps/dist/index.js:69570:5)\n    at async Object.<anonym
ous> (/Users/ben/dylibso/xtprps/dist/index.js:69645:16)
```

**Comment by chrisdickinson** [comment]
#80 should fix this!
